" Autoreload .vimrc and .vim/vimrc {{{
autocmd! BufWritePost .vimrc source %
autocmd! BufWritePost vimrc source %
" }}}

" vundle settings {{{
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" }}}

" VIM Plugins {{{
Plugin 'gmarik/Vundle.vim'

autocmd BufWritePre vimrc :g/PluginStart/+1,/PluginEnd/-1 sort ui

" Plugin 'django.vim'
" Plugin 'funorpain/vim-cpplint'
" Plugin 'FuzzyFinder'
" Plugin 'honza/vim-snippets'
" Plugin 'jistr/vim-nerdtree-tabs'
" Plugin 'klen/python-mode'
" Plugin 'Shougo/unite.vim'
" Plugin 'tell-k/vim-autopep8'
" PluginStart {{{
Plugin 'airblade/vim-gitgutter'
Plugin 'altercation/vim-colors-solarized'
Plugin 'bling/vim-airline'
Plugin 'c.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'fatih/vim-go'
Plugin 'garbas/vim-snipmate'
Plugin 'godlygeek/tabular'
Plugin 'gregsexton/MatchTag'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'jmcantrell/vim-virtualenv'
Plugin 'kien/ctrlp.vim'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'L9'
Plugin 'lervag/vim-latex'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'majutsushi/tagbar'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'marijnh/tern_for_vim'
Plugin 'mattn/emmet-vim'
Plugin 'moll/vim-bbye'
Plugin 'nathanaelkane/vim-indent-guides'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'pangloss/vim-javascript'
Plugin 'Raimondi/delimitMate'
Plugin 'rking/ag.vim'
Plugin 'rust-lang/rust.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'Shougo/unite.vim'
Plugin 'Shougo/vimfiler.vim'
Plugin 'sjl/badwolf'
Plugin 'sjl/gundo.vim'
Plugin 'sukima/xmledit'
Plugin 'szw/vim-tags'
Plugin 'tomtom/tlib_vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'Valloric/YouCompleteMe'
" }}} PluginEnd
" }}}

" General settings {{{
let mapleader = ","
nnoremap ; :
scriptencoding utf-8
set encoding=utf-8
set timeoutlen=500
set mouse=a
set clipboard=unnamedplus
set autoread               " Autoreload
set hidden                 " set Vim like any other editor (butffers, etc)

set modelines=1
set shell=/bin/bash
" set switchbuf+=usetab,newtab

set number                 " Line numbers
set numberwidth=6
set tw=79                  " width of document (used by gd)
set colorcolumn=80
set list                   " show EOL
set listchars=tab:▸\ ,eol:¬
set showcmd
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.

syntax on
syntax sync minlines=256

set guifont=Inconsolata-dz\ for\ Powerline\ Medium\ 10
set guioptions-=T
set guioptions-=mrL

set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max

set backspace=indent,eol,start    " Backspace in normal mode
set history=700
set undolevels=700

set nowrap                 " don't automatically wrap on load
set fo-=t                  " don't automatically wrap text when typing
set linebreak              " Wrap lines at convenient points

set scrolloff=2

autocmd BufWritePre * :%s/\s\+$//e      " Trim trailing whitespaces
" }}}

" Line return {{{
augroup line_return
  au!
  au BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \     execute 'normal! g`"zvzz' |
    \ endif
augroup END
" }}}

" Indentation {{{
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
filetype plugin on
filetype indent on

" }}}

" Swap backup {{{
set backup
set backupdir=~/.vim-tmp//,~/.tmp//,~/tmp//,/var/tmp//,/tmp//
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp//,~/.tmp//,~/tmp//,/var/tmp//,/tmp//
set writebackup
" }}}

" Searching {{{
set hlsearch
set incsearch
set ignorecase
set smartcase

nnoremap n nzzzv
nnoremap N Nzzzv

nnoremap * *<C-o>

" Show search results in quickfix
nnoremap <silent> <leader>/ :execute 'vimgrep /'.@/.'/g %'<CR>:copen<CR>

" }}}

" Color scheme {{{
set t_Co=256

let g:badwolf_darkgutter = 1
let g:badwolf_tabline = 3
colorscheme badwolf

if has('x11')
    highlight IndentGuidesEven ctermbg=236
    highlight IndentGuidesOdd ctermbg=237
endif

if has('gui_running')
  colorscheme molokai
endif

" Highlight VCS conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'
" }}}

" Highlighting {{{
set cursorline
set cursorcolumn
" }}}

" Cursor settings {{{
au InsertEnter * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ibeam"
au InsertLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape block"
" au VimLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape underline"
" au VimEnter * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape block"

" Cursor automove issue
" au InsertEnter * call cursor(getpos('.')[1], getpos('.')[2]+1)
" }}}

" Vim sessions {{{
"function! MakeSession()
  "let b:sessiondir = $HOME . '/.vim/sessions' . getcwd()
  "if (filewritable(b:sessiondir) != 2)
    "exe 'silent !mkdir -p ' b:sessiondir
    "redraw!
  "endif
  "let b:filename = b:sessiondir . '/session.vim'
  "exe 'mksession! ' . b:filename
"endfunction

"function! LoadSession()
  "let b:sessiondir = $HOME . '/.vim/sessions' . getcwd()
  "let b:sessionfile = b:sessiondir . '/session.vim'
  "if (filereadable(b:sessionfile))
    "exe 'source ' b:sessionfile
  "else
    "echo 'No session loaded.'
  "endif
"endfunction
"au VimEnter * nested :call LoadSession()
"au VimLeave * :call MakeSession()
" }}}

" Shortcuts functions {{{
" General shortcut creation function
function! CreateCommandShortcut(shortcut, command)
    exe 'nnoremap ' . a:shortcut . ' ' . a:command . '<Enter>'
    exe 'inoremap ' . a:shortcut . ' <C-\><C-O>' . a:command . '<Enter>'
    exe 'vnoremap ' . a:shortcut . ' <Esc>' . a:command . '<Enter>'
endfunction

function! CreateShortcut(shortcut, command, ...)
    exe 'nnoremap ' . a:shortcut . ' ' . a:command
    exe 'inoremap ' . a:shortcut . ' <Esc>' . a:command
    if a:0 > 0
        exe 'vnoremap ' . a:shortcut . ' ' . a:command
    else
        exe 'vnoremap ' . a:shortcut . ' <Esc>' . a:command
    end
endfunction
" }}}

" Shortcut Definitions {{{
call CreateCommandShortcut('<C-s>', ':update')     " Ctrl-S save

call CreateCommandShortcut('<C-q>', ':Bdelete')
call CreateCommandShortcut('<M-q>', ':q')           " Ctrl-Q close tab

call CreateCommandShortcut('<C-;>', ':nohl')        " Ctrl-L close search

call CreateCommandShortcut('<C-n>', ':NERDTreeToggle')

vnoremap <C-c> y
" vnoremap <C-v> p
" nnoremap <C-v> p
" inoremap <C-v> <LEFT><C-\><C-o>p
inoremap <C-w> <Esc><C-w>

call CreateShortcut('<C-PageUp>', ':bnext<CR>')
call CreateShortcut('<C-PageDown>', ':bprevious<CR>')

nnoremap <leader>u :GundoToggle<CR>
nnoremap <leader>a :Ag<SPACE>
nnoremap <leader>p :CtrlPTag<CR>
nnoremap <silent> <Leader>tb :TagbarToggle<CR>
nnoremap <leader>f :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
nnoremap <leader>t :tag "\b<C-R><C-W>\b"<CR>:cw<CR>

nnoremap H ^
nnoremap L $
inoremap <C-l> <C-x><C-l>
inoremap <C-f> <C-x><C-f>
" }}}

" Word highligher {{{
" Highlight Word {{{
"
" This mini-plugin provides a few mappings for highlighting words temporarily.
"
" Sometimes you're looking at a hairy piece of code and would like a certain
" word or two to stand out temporarily.  You can search for it, but that only
" gives you one color of highlighting.  Now you can use <leader>N where N is
" a number from 1-6 to highlight the current word in a specific color.

function! HiInterestingWord(n) " {{{
    " Save our location.
    normal! mz

    " Yank the current word into the z register.
    normal! "zyiw

    " Calculate an arbitrary match ID.  Hopefully nothing else is using it.
    let mid = 86750 + a:n

    " Clear existing matches, but don't worry if they don't exist.
    silent! call matchdelete(mid)

    " Construct a literal pattern that has to match at boundaries.
    let pat = '\V\<' . escape(@z, '\') . '\>'

    " Actually match the words.
    call matchadd("InterestingWord" . a:n, pat, 1, mid)

    " Move back to our original location.
    normal! `z
endfunction " }}}

" Mappings {{{

nnoremap <silent> <leader>1 :call HiInterestingWord(1)<cr>
nnoremap <silent> <leader>2 :call HiInterestingWord(2)<cr>
nnoremap <silent> <leader>3 :call HiInterestingWord(3)<cr>
nnoremap <silent> <leader>4 :call HiInterestingWord(4)<cr>
nnoremap <silent> <leader>5 :call HiInterestingWord(5)<cr>
nnoremap <silent> <leader>6 :call HiInterestingWord(6)<cr>

" }}}
" Default Highlights {{{

hi def InterestingWord1 guifg=#000000 ctermfg=16 guibg=#ffa724 ctermbg=214
hi def InterestingWord2 guifg=#000000 ctermfg=16 guibg=#aeee00 ctermbg=154
hi def InterestingWord3 guifg=#000000 ctermfg=16 guibg=#8cffba ctermbg=121
hi def InterestingWord4 guifg=#000000 ctermfg=16 guibg=#b88853 ctermbg=137
hi def InterestingWord5 guifg=#000000 ctermfg=16 guibg=#ff9eb8 ctermbg=211
hi def InterestingWord6 guifg=#000000 ctermfg=16 guibg=#ff2c4b ctermbg=195

" }}}
" }}}
" }}}

" Hard mode {{{
" inoremap <Up> <NOP>
" inoremap <Down> <NOP>
" inoremap <Left> <NOP>
" inoremap <Right> <NOP>
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
" }}}

" Quick file access {{{
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" }}}

" Plugin Settings {{{

" vim-airline {{{
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_theme='badwolf'
set laststatus=2           " Turn on vim-airline
" }}}

" Ag.vim silver-searcher {{{
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor
endif
" }}}

" CtrlP {{{
let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0
if executable('ag')
    let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'
    let g:ctrlp_use_caching = 0
endif
let g:ctrlp_max_files=0
" }}}

" VimFiler {{{
let g:vimfiler_as_default_explorer = 1
let g:vimfiler_tree_indentation = 2
let g:vimfiler_tree_leaf_icon = ' '
let g:vimfiler_tree_opened_icon = '▾'
let g:vimfiler_tree_closed_icon = '▸'
let g:vimfiler_file_icon = '-'
let g:vimfiler_marked_file_icon = '*'

" }}}

" NerdTree {{{
let NERDTreeShowHidden=0
let g:NERDTreeChDirMode=2

set fillchars+=vert:\ | let g:NERDTreeMirror=1

" nerdtree-tabs {{{
" let g:nerdtree_tabs_open_on_console_startup=1
" }}}
" }}}

" vim-indent-guides {{{
" let g:indent_guides_start_level=1
" let g:indent_guides_guide_size=4
let g:indent_guides_enable_on_vim_startup=1

" }}}

" Syntastic {{{
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_python_checkers = ['flake8']
let g:syntastic_cpp_compiler_options = '-std=c++11'

let g:syntastic_javascript_checkers = ['jshint', 'jslint', 'gjslint']
" }}}

" YouCompleteMe {{{
let g:ycm_key_list_select_completion = ['<TAB>']
let g:ycm_key_list_previous_completion = ['<S-TAB>']
let g:ycm_add_preview_to_completeopt = 1
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_complete_in_comments = 1
let g:ycm_register_as_syntastic_checker = 1
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_global_ycm_extra_conf = "~/.vim/.ycm_extra_conf.py"


let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
let g:jedi#use_splits_not_buffers = "bottom"

" }}}

" SnipMate {{{
imap <C-i> <Plug>snipMateNextOrTrigger
" }}}

" c.vim {{{
let g:C_UseTool_cmake = 'yes'
let g:C_UseTool_doxygen = 'yes'

" }}}

" Eclim {{{
let g:EclimCompletionMethod = 'omnifunc'
" }}}

" Tern {{{
let tern#is_show_argument_hints_enabled = 1
" }}}

" Raindow Parantheses {{{
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
" }}}
" }}}

" Machine specific settings {{{
source ~/.machine_vimrc
" }}}

" Language specific settings {{{
autocmd FileType html source ~/.vim/html.vimrc
autocmd FileType ng.html source ~/.vim/html.vimrc
autocmd FileType java source ~/.vim/java.vimrc
" }}}

" Startup {{{
" Since we store session, no need to call NERDTree on start.
" autocmd vimenter * NERDTree
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
call vundle#end()

" }}}

" vim:foldmethod=marker:foldlevel=0
