" Autoreload .vimrc and .vim/vimrc
autocmd! BufWritePost .vimrc source %
autocmd! BufWritePost vimrc source %

" vundle settings
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

" =========== Plugin: Operational plugins ===============
Plugin 'bling/vim-airline'
Plugin 'kien/ctrlp.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'Valloric/YouCompleteMe'
Plugin 'tpope/vim-fugitive'


" ============== GENERAL CONFIG ==============
set number                        " Line numbers
set backspace=indent,eol,start    " Backspace in normal mode
set autoread                      " Autoreload
set history=700
set undolevels=700
set hidden                 " set Vim like any other editor (butffers, etc)

set tw=79                  " width of document (used by gd)
set colorcolumn=80
set nowrap                 " don't automatically wrap on load
set fo-=t                  " don't automatically wrap text when typing
set linebreak              " Wrap lines at convenient points
set scrolloff=2

set laststatus=2           " Turn on vim-airline

set list                   " show EOL
autocmd BufWritePre * :%s/\s\+$//e      " Trim trailing whitespaces

syntax on


" ============= Turn Off Swap Files =========
set noswapfile
set nobackup
set nowb

" ================ Indentation ======================
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab
filetype plugin on
filetype indent on


" ============== Color Scheme ---------------------
set t_Co=256
colorscheme Tomorrow-Night-Eighties

" =============== Highlighting =====================
set cursorline
set cursorcolumn

highlight Cursor guifg=white guibg=black
highlight iCursor guifg=white guibg=steelblue
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver100-iCursor
set guicursor+=n-v-c:blinkon0
set guicursor+=i:blinkwait10

au InsertEnter * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ibeam"
au InsertLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape block"
au VimLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape underline"
au VimEnter * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape block"

" ============== Shortcuts ========================


" =========== Plugin Configs ======================

" ======= vim-airline ===========
let g:airline_powerline_fonts=1
set timeoutlen=50

" ============== Startup =======================
autocmd vimenter * NERDTree
autocmd vimenter * NERDTreeTabsOpen


call vundle#end()
