call plug#begin('~/.vim/bundle')
Plug 'Shougo/unite.vim'
Plug 'liuchengxu/vim-better-default'
if !filereadable(expand('~/.google-office')) 
  Plug 'Valloric/YouCompleteMe' 
endif
call plug#end()

let g:vim_better_default_minimum = 1
source ~/.machine_vimrc
